### PR TITLE
Update memo format and make memo updatable

### PR DESCRIPTION
**Pull request by yoomee1313**
This PR updates memo format of the kip-103 and kip-160 and adds enabling editing memo section in kip-160.
* kip-103: revise memo format of a Info-log to match with the contract memo format
* kip-160: add new memo format. The reason of introducing new memo format is to get the additional balance data to calculate burnt amount directly.
* kip-160: added `pendingMemo` stroage and `setPendingMemo` method. finalizeContract doesn't accept memo string anymore.

### CODE REVIEW

**Review by blukat29 — APPROVED** [review]

**Comment by Sotatek-TinnNguyen** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Sotatek-TinnNguyen** [comment]
Hi @yoomee1313 can you sign the CLA

**Comment by yoomee1313** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by yoomee1313** [comment]
@Sotatek-TinnNguyen I have signed the CLA and CLA works well. However, Check Links task fails.. Do you know why it fails?
```
Run peter-evans/create-issue-from-file@v4
Error: Resource not accessible by integration
```

**Comment by Sotatek-TinnNguyen** [comment]
@yoomee1313 I think this issue in [here](https://github.com/peter-evans/create-issue-from-file/issues/1220#issuecomment-1705418862): Maybe we need to use the circleCI

**Comment by yoomee1313** [comment]
@Sotatek-TinnNguyen I(yoomee1313) created this PR(https://github.com/kaiachain/kips/pull/6) and check-link github action is passed.
I think it's related to this setting: https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks#about-workflow-runs-from-public-forks
Can the change of this setting solve the problem..??

**Comment by Sotatek-TinnNguyen** [comment]
the github action works fine with PR inside repo but can not work with PR from fork repo @yoomee1313

**Comment by yoomee1313** [comment]
I'll merge this PR since check I have checked that check links actually works.

**Pull request merged**
